<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="41443" started-at="2020-08-31T11:06:56Z" finished-at="2020-08-31T11:07:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="41443" started-at="2020-08-31T11:06:56Z" finished-at="2020-08-31T11:07:37Z">
      <class name="com.alliance.qa.testcases.DataProviderTest">
        <test-method status="PASS" signature="startUpMethed()[pri:0, instance:com.alliance.qa.testcases.DataProviderTest@46d56d67]" name="startUpMethed" is-config="true" duration-ms="41229" started-at="2020-08-31T16:36:56Z" finished-at="2020-08-31T16:37:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUpMethed -->
        <test-method status="FAIL" signature="logInAndFillData(java.lang.String, java.lang.String)[pri:0, instance:com.alliance.qa.testcases.DataProviderTest@46d56d67]" name="logInAndFillData" duration-ms="201" started-at="2020-08-31T16:37:37Z" data-provider="getData" finished-at="2020-08-31T16:37:37Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: logInAndFillData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [([Ljava.lang.Object;)[Ljava.lang.Object;@5b6ec132]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: logInAndFillData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [([Ljava.lang.Object;)[Ljava.lang.Object;@5b6ec132]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1278)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1171)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInAndFillData -->
        <test-method status="PASS" signature="termDown()[pri:0, instance:com.alliance.qa.testcases.DataProviderTest@46d56d67]" name="termDown" is-config="true" duration-ms="0" started-at="2020-08-31T16:37:37Z" finished-at="2020-08-31T16:37:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- termDown -->
      </class> <!-- com.alliance.qa.testcases.DataProviderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
